### ISSUE TITLE
Pulseaudio you have

### ISSUE THREAD

**Issue by GERMANOCARELLA** [therealkenc/-#1]
Hi,
I read you have modified pulseaudio to work in bash on windwos. It's true? How can I modify it, or have you a copy?

**Comment by therealkenc** [comment]
There's a gist with build instructions [here](https://gist.github.com/therealkenc/5dae7eefbacb0083e485348bd25ee33c), but they are probably overkill. @aseering put together a ppa. Basically have a look at issue [#486](https://github.com/Microsoft/BashOnWindows/issues/486#issuecomment-234930031) from July 25 down and it has the details.

**Comment by therealkenc** [comment]
Here's the ppa: 

https://launchpad.net/~aseering/+archive/ubuntu/wsl-pulseaudio
